name: scaffold_gradient_background
description: A widget that works like a scaffold, except that you can set a gradient as background.
version: 1.0.2+1
homepage: https://github.com/Tomic-Riedel/gradient_scaffold

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
